# Generated by Django 4.1.3 on 2023-01-23 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photopost",
            old_name="titole",
            new_name="title",
        ),
    ]
